[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
pdf = [
	# xdg-open이 비동기라서 pdf순서대로 열려면 sleep 필요
	{ run = 'for f in "$@"; do xdg-open "$f" >/dev/null 2>&1 & sleep 0.1; done', desc = "Open PDFs sequentially", orphan = true }
]
open = [
    { run = 'xdg-open "$@"', desc = "Open", orphan = true }
]

[open]
prepend_rules = [
	{ name = "*.svg", use = "edit" },
	{ name = "*.pdf", use = "pdf" },
]
